CREATE TABLE ssl_certificates (
  id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  domain_id   BIGINT UNSIGNED NOT NULL UNIQUE,
  type        ENUM('letsencrypt', 'custom') NOT NULL,
  cert_path   VARCHAR(512) NOT NULL,
  key_path    VARCHAR(512) NOT NULL,
  expires_at  TIMESTAMP NOT NULL,
  auto_renew  BOOLEAN NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
