CREATE TABLE admin_allowed_ips (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ip_cidr VARCHAR(64) NOT NULL,
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ip_cidr (ip_cidr)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
