package filebrowser

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	osuser "os/user"
	"path/filepath"
	"sort"
	"strconv"
	"sync"

	"github.com/zenspanel/zenspanel/agent/safe"
)

const (
	// nginxMapConf is placed in conf.d/ so nginx includes it in the http
	// context — the only context where map{} directives are valid.
	nginxMapConf = "/etc/nginx/conf.d/zenspanel-fb-ports.conf"

	// portMapJSON is the JSON source of truth for port assignments.
	// We derive the Nginx map file from it on every change instead of
	// parsing Nginx syntax.
	portMapJSON = "/etc/nginx/zenspanel/fb-ports.json"

	fbBin = "/usr/local/bin/filebrowser"
)

// unitPath returns the systemd service unit file path for a panel user's
// dedicated FileBrowser instance.
func unitPath(username string) string {
	return "/etc/systemd/system/zenspanel-fb-" + username + ".service"
}

// userPort derives the FileBrowser TCP listen port from the Linux UID.
// UIDs are assigned in range 10 000–60 000 by the agent; adding 100
// gives ports 10 100–60 100. Ports below 32 768 (the Linux ephemeral
// range floor on most systems) are guaranteed not to collide with
// ephemeral connections. Panels with more than ~22 000 users should
// raise net.ipv4.ip_local_port_range to start above 60 100.
func userPort(uid int) int {
	return uid + 100
}

// mu serialises concurrent writes to the Nginx map files.
var mu sync.Mutex

// CreateUser provisions a dedicated FileBrowser process for a panel user.
//
// Each instance runs as the panel user (User=<username> in the systemd
// unit), so every file FileBrowser creates is owned by that user from
// the moment of creation — no chown timer, no root-owned files, no race
// window where PHP cannot write to uploaded content.
//
// The FileBrowser SQLite DB is initialised via the CLI *before* the
// service starts. CLI and service both hold an exclusive write lock on
// the DB; initialising beforehand avoids the deadlock documented in the
// previous single-instance design.
// CreateUser provisions a dedicated FileBrowser instance for a panel user.
// isAdmin=true: runs as root, browse root="/", full FileBrowser admin perms
// (settings + storage visible) — mirrors cPanel WHM File Manager.
// isAdmin=false: runs as the panel user, scoped to their home dir, with
// perm.admin stripped (no settings page, no storage usage widget).
func CreateUser(username, homeBase string, isAdmin bool) error {
	if err := safe.Username(username); err != nil {
		return err
	}

	u, err := osuser.Lookup(username)
	if err != nil {
		return fmt.Errorf("lookup %s: %w", username, err)
	}
	uid, err := strconv.Atoi(u.Uid)
	if err != nil {
		return fmt.Errorf("parse uid: %w", err)
	}
	gid, err := strconv.Atoi(u.Gid)
	if err != nil {
		return fmt.Errorf("parse gid: %w", err)
	}

	port := userPort(uid)

	var homeDir, dbPath string
	if isAdmin {
		// Admin DB lives in /root — never inside a panel user home that
		// could be deleted, and accessible only by root.
		homeDir = "/"
		dbPath = "/root/.zenspanel-fb-" + username + ".db"
	} else {
		homeDir = filepath.Join(homeBase, username)
		dbPath = filepath.Join(homeDir, ".zenspanel-fb.db")
	}

	// Idempotent: only initialise the DB when it doesn't already exist.
	if _, statErr := os.Stat(dbPath); os.IsNotExist(statErr) {
		if err := initDB(dbPath, homeDir, port, username, isAdmin); err != nil {
			return err
		}
		if !isAdmin {
			if err := os.Chown(dbPath, uid, gid); err != nil {
				return fmt.Errorf("chown db: %w", err)
			}
		}
	}

	// Admin unit: User=root (full VM access).
	// User unit:  User=<username> (files created are owned correctly).
	serviceUser := username
	if isAdmin {
		serviceUser = "root"
	}
	unit := "# Auto-generated by ZensPanel agent — do not edit.\n" +
		"[Unit]\n" +
		"Description=ZensPanel FileBrowser — " + username + "\n" +
		"After=network.target\n\n" +
		"[Service]\n" +
		"Type=simple\n" +
		"User=" + serviceUser + "\n" +
		"ExecStart=" + fbBin + " --database " + dbPath + "\n" +
		"Restart=on-failure\n" +
		"RestartSec=5\n\n" +
		"[Install]\n" +
		"WantedBy=multi-user.target\n"

	if err := os.WriteFile(unitPath(username), []byte(unit), 0644); err != nil {
		return fmt.Errorf("write unit: %w", err)
	}

	svc := "zenspanel-fb-" + username + ".service"
	for _, args := range [][]string{
		{"systemctl", "daemon-reload"},
		{"systemctl", "enable", "--quiet", svc},
		{"systemctl", "start", svc},
	} {
		if out, cmdErr := exec.Command(args[0], args[1:]...).CombinedOutput(); cmdErr != nil {
			return fmt.Errorf("%v: %w: %s", args, cmdErr, out)
		}
	}

	if err := addToPortMap(username, port); err != nil {
		return fmt.Errorf("update port map: %w", err)
	}
	return reloadNginx()
}

// DeleteUser stops and removes the per-user FileBrowser service and
// removes its entry from the Nginx port map. The DB file lives inside
// the user's home directory (~/.zenspanel-fb.db) and is removed as
// part of the home directory deletion — no explicit DB cleanup here.
func DeleteUser(username string) error {
	if err := safe.Username(username); err != nil {
		return err
	}
	svc := "zenspanel-fb-" + username + ".service"
	// Best-effort: non-fatal if the unit never existed.
	exec.Command("systemctl", "stop", svc).Run()    //nolint:errcheck
	exec.Command("systemctl", "disable", svc).Run() //nolint:errcheck
	os.Remove(unitPath(username))
	exec.Command("systemctl", "daemon-reload").Run() //nolint:errcheck

	if err := removeFromPortMap(username); err != nil {
		return fmt.Errorf("update port map: %w", err)
	}
	return reloadNginx()
}

// initDB runs the FileBrowser CLI to create a fresh per-user DB with
// proxy auth, the correct home root, and the user's listen port baked in.
func initDB(dbPath, homeDir string, port int, username string, isAdmin bool) error {
	pw := make([]byte, 16)
	if _, err := rand.Read(pw); err != nil {
		return fmt.Errorf("rand: %w", err)
	}
	password := hex.EncodeToString(pw)

	// Admin gets perm.admin=true so Settings and Storage Usage are visible.
	// Regular users get perm.admin=false — those UI sections are hidden.
	permAdmin := "false"
	if isAdmin {
		permAdmin = "true"
	}

	cmds := [][]string{
		{fbBin, "--database=" + dbPath, "config", "init"},
		{fbBin, "--database=" + dbPath, "config", "set",
			"--address", "127.0.0.1",
			"--port", strconv.Itoa(port),
			"--root", homeDir,
			"--baseurl", "/filebrowser",
			"--auth.method=proxy",
			"--auth.header=X-Auth-User",
		},
		{fbBin, "--database=" + dbPath, "users", "add",
			username, password,
			"--perm.admin=" + permAdmin,
			"--perm.create=true",
			"--perm.rename=true",
			"--perm.modify=true",
			"--perm.delete=true",
			"--perm.share=false",
			"--perm.download=true",
			"--scope", "/",
		},
	}
	for _, args := range cmds {
		if out, err := exec.Command(args[0], args[1:]...).CombinedOutput(); err != nil {
			return fmt.Errorf("filebrowser %s: %w: %s", args[2], err, out)
		}
	}
	return nil
}

// ── Nginx port map ────────────────────────────────────────────────────

type portMap map[string]int

func readPortMap() (portMap, error) {
	pm := make(portMap)
	data, err := os.ReadFile(portMapJSON)
	if os.IsNotExist(err) {
		return pm, nil
	}
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(data, &pm); err != nil {
		return nil, fmt.Errorf("parse port map: %w", err)
	}
	return pm, nil
}

func writePortMap(pm portMap) error {
	if err := os.MkdirAll(filepath.Dir(portMapJSON), 0755); err != nil {
		return err
	}
	data, _ := json.Marshal(pm)
	if err := os.WriteFile(portMapJSON, data, 0644); err != nil {
		return err
	}
	return writeNginxMapConf(pm)
}

// writeNginxMapConf renders the Nginx map block from the current port
// assignments. The map{} directive must be in the http context; placing
// this file in conf.d/ satisfies that — nginx.conf includes conf.d/*.conf
// inside the http block on all standard Ubuntu installs.
func writeNginxMapConf(pm portMap) error {
	if err := os.MkdirAll(filepath.Dir(nginxMapConf), 0755); err != nil {
		return err
	}
	var buf bytes.Buffer
	buf.WriteString("# Auto-generated by ZensPanel agent — do not edit.\n")
	buf.WriteString("map $fb_user $fb_port {\n")
	buf.WriteString("    default 0;\n")
	users := make([]string, 0, len(pm))
	for u := range pm {
		users = append(users, u)
	}
	sort.Strings(users)
	for _, u := range users {
		fmt.Fprintf(&buf, "    %-30s %d;\n", u, pm[u])
	}
	buf.WriteString("}\n")
	return os.WriteFile(nginxMapConf, buf.Bytes(), 0644)
}

func addToPortMap(username string, port int) error {
	mu.Lock()
	defer mu.Unlock()
	pm, err := readPortMap()
	if err != nil {
		pm = make(portMap)
	}
	pm[username] = port
	return writePortMap(pm)
}

func removeFromPortMap(username string) error {
	mu.Lock()
	defer mu.Unlock()
	pm, err := readPortMap()
	if err != nil {
		return err
	}
	delete(pm, username)
	return writePortMap(pm)
}

func reloadNginx() error {
	if out, err := exec.Command("nginx", "-s", "reload").CombinedOutput(); err != nil {
		return fmt.Errorf("nginx reload: %w: %s", err, out)
	}
	return nil
}
